name: iot_simulacao
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # Versão mais recente da biblioteca http
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
